### ISSUE TITLE
ADB restore of pack-kk does not work on Android 4.4.2 (KitKat)

### ISSUE THREAD

**Issue by andreassjoberg** [nelenkov/android-backup-extractor#11]
Device: Nexus 4
Build: KOT49H (Android 4.4.2)

Performed backup using (encrypted with password):
adb backup -apk -shared -all -f backup.ab

Performed unpack (successfully):
java -jar abe.jar unpack backup.ab backup.tar

Extracted the tar-file and removed one directory (which the restore stuck on during adb restore of the original backup.ab file).
Created a new tar file (with the failing directory removed).

Performed pack:
java -jar abe.jar pack-kk new-backup.tar new-backup.ab

Tried restore back to device, like:
adb restore new-backup.ab

I get prompted for password on the device, but the restore cancels immediately.

I tried packing both with and without setting an encryption password, neither works.

**Comment by jacobcat** [comment]
I'm using the same Android version 4.4.2, but with a Samsung Note 3. I came across this very same problem, but I was able to make it work.

The pack-kk command works, except that my device doesn't recognize the Device version 2 on the second line of the .ab file. So I changed it to 1, and it now restores my backup successfully.

Hope this helps.
