### ISSUE TITLE
How to use in Ubuntu 22.04?

### ISSUE THREAD

**Issue by OneEyedTiamat** [nelenkov/android-backup-extractor#123]
Hello.

When using the following commands in the Ubuntu 22.04 terminal, I get an error message saying the abe command isn’t found and should be installed.

chmod +x abe.jar

java -jar abe.jar

abe unpack color.note.adb

I shouldn’t need an abe command as far as I can tell, I have the abe.jar file (I opened the folder in terminal, the folder only has the files abe.jar and color.note.adb) and I’m trying to tell the terminal to use it. What did I do wrong?

(I can copy paste the error message, but it's not in English)

**Comment by nelenkov** [comment]
You don't really need the script, `java -jar abe.jar unpack ...` should be enough.

**Comment by OneEyedTiamat** [comment]
> java -jar abe.jar unpack

Here is the output:

java -jar abe.jar unpack color.note.adb
Usage:
  unpack:	abe unpack	<backup.ab> <backup.tar> [password]
  pack:		abe pack	<backup.tar> <backup.ab> [password]
  pack for 4.4:	abe pack-kk	<backup.tar> <backup.ab> [password]
If the filename is `-`, then data is read from standard input
or written to standard output.
Envvar ABE_PASSWD is tried when password is not given

**Comment by nelenkov** [comment]
That means it's working, you just have to specify the output tar file.
