### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by OneEyedTiamat** [nelenkov/android-backup-extractor#124]
Hello,

I'm still trying to get abe.jar to unpack a file. Here is my command: java -jar abe.jar abe unpack color.note.adb color.note.tar [password]

(I tried the app's password, no password, and the default password, with and without [], I can’t try phone password because there isn’t a password, just a shape and fingerprints)

It gives me the possible commands, but no file, so clearly I’m still doing something wrong. What password am I supposed to use here? The app's password? A password set when I got the color.note.adb file? Something else? Could the issue be something else?

Thanks.

**Comment by OneEyedTiamat** [comment]
> If you want to use Linux, spend some time learning the basics of command line and your shell. Also check the readme and blog post to understand how Android backups work. It takes some time, but is eventually easier than trying random things.
> 
> `[password]` here means the password is optional -- if the backup is not encrypted there is no password. Implementation might be different on some devices, but typically you are asked for a password when you create the backup. If didn't specify one, the backup is probably not encrypted.
> 
> Look at the first lines of the .ab file, that would also give you a hint if it's encrypted. If it is, you need to specify the password.

I'm new at using jar files, and it's been a few years since I last used Ubuntu. I'm quite rusty.

The first lines of the file are :

ANDROID BACKUP
5
1
none

There's also a last line I don't really get, but that I can also post here if required. The device isn't encrypted, and the file shouldn't be either, but it's possible that it is.

**Comment by nelenkov** [comment]
Looks like the backup is not encrypted, so it should work without specifying a password.

**Comment by OneEyedTiamat** [comment]
> Looks like the backup is not encrypted, so it should work without specifying a password.

Then what could be the issue? Again, the command `java -jar abe.jar abe unpack color.note.adb color.note.tar` doesn't seem to do much other than just display 

> Usage:
>   unpack:	abe unpack	<backup.ab> <backup.tar> [password]
>   pack:		abe pack	<backup.tar> <backup.ab> [password]
>   pack for 4.4:	abe pack-kk	<backup.tar> <backup.ab> [password]
> If the filename is `-`, then data is read from standard input
> or written to standard output.
> Envvar ABE_PASSWD is tried when password is not given
> 

I'm not sure what else I can do.

**Comment by nelenkov** [comment]
Not sure what you have downloaded, but either use the shell script (`abe`) or the jar file, not both in the same command.

If using the jar file: `java -jar abe.jar unpack color.note.adb color.note.tar`

**Comment by nelenkov** [comment]
Sure. But looking at the readme and checking out what's in the script file would have given you the same result, much faster.
