### ISSUE TITLE
Illegal key size

### ISSUE THREAD

**Issue by dlamblin** [nelenkov/android-backup-extractor#34]
I just made 2 ab files from Android 5.0.1 on a Nexus 9. One with -system -all -apk -shared and one with -nosystem -all -apk -shared. When using the extractor I get the following:

    $ java -jar ~/src/android-backup-extractor/build/libs/abe-all.jar unpack n9_apk_shared_nosystem_all_20150815.ab <pwd>
    This backup is encrypted, please provide the password
    Password: 
    Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
    	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:203)
    	at org.nick.abe.Main.main(Main.java:40)
    Caused by: java.security.InvalidKeyException: Illegal key size
    	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
    	at javax.crypto.Cipher.implInit(Cipher.java:805)
    	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
    	at javax.crypto.Cipher.init(Cipher.java:1396)
    	at javax.crypto.Cipher.init(Cipher.java:1327)
    	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:118)
    	... 1 more

I had a desktop backup password set (which is what I gave on the command line) and I had an encryption password set to the same, given interactively.

I suspect that either the 5.0 format is different than expected, or installing the bouncy castle bcprov-jdk15on-152.jar wasn't quite right...

I used ./gradlew after putting the jar in lib, and it seems to have made the right abe-all.jar... yet I get the above.

**Comment by nelenkov** [comment]
You need to install the unlimited strength JCA policy, see README.

**Comment by dlamblin** [comment]
Thanks, so... I missed that in the README because it wasn't clear on reading the file.
With the requirements on one line like it is, I read "Java 7" as, okay yes, I got the JDK8 so I have at least Java 7, and the text after that as some detail explaining why Java 7 is needed, IE that is included in Java 7. It was unclear that you meant there were two requirements, Java 7 or better and the Java Cryptography Extension (JCE) Unlimited.

May I suggest both that you list these as two requirements and that you do not abbreviate JCE as it's so much like JRE etc. ?

For future reference, should anyone search for the same issue, I'm going to document the steps for installing this on Mac OS X:
  1. browse to http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html and accept the license then download the file UnlimitedJCEPolicyJDK7.zip
  2. the following in a terminal:

        cd ~/Downloads
        unzip UnlimitedJCEPolicyJDK7.zip
        JAVAHOME=`/usr/libexec/java_home`
        sudo mv $JAVAHOME/jre/lib/security/US_export_policy.jar \
                $JAVAHOME/jre/lib/security/US_export_policy_orig.jar
        sudo mv $JAVAHOME/jre/lib/security/local_policy.jar \
                $JAVAHOME/jre/lib/security/local_policy_orig.jar
        sudo cp UnlimitedJCEPolicy/*.jar $JAVAHOME/jre/lib/security/
        rm -r UnlimitedJCEPolicy UnlimitedJCEPolicyJDK7.zip
        cd
        git clone https://github.com/nelenkov/android-backup-extractor.git abe
        cd abe/lib
        curl -O http://www.bouncycastle.org/download/bcprov-jdk15on-152.jar
        ./gradlew
        java -jar build/libs/abe-all.jar

That should show you standard usage, which you can also see without JCE, but you can't unpack without JCE.

Thanks for writing the tool, I hope I can use it to break down and repack a -all backup with only the parts I want to restore...
