### ISSUE TITLE
Empty tar file produced

### ISSUE THREAD

**Issue by codecowboy** [nelenkov/android-backup-extractor#35]
I tried this on a backup from a Hudl Tablet (4.4.2). The tar file produced is empty:

```
codecowboy@codecowboy-P5E3-Premium:~/Android/Sdk/platform-tools/android-backup-extractor$ java -jar abe.jar unpack ../backup.ab ../backup.tar "123"
Calculated MK checksum (use UTF-8: false): 4FC9F7082543089D608F6E5E6C53DC7E7FEDD41208AE863A63EF28AA5202CFB1
Checksum does not match.
Calculated MK checksum (use UTF-8: false): DD612A26A43A37294ABA86689564C5CD53740ABD42A523179B13A3A3A0D1AE40
1024 bytes written to ../backup.tar
```

**Comment by nelenkov** [comment]
If the chekcsum doesn't match, either the file is corrupt or the password is not correct. Does it work with an unencrypted backup file?

**Comment by codecowboy** [comment]
Not sure. I gave up on this when there was a suggestion that some versions of Android had a bug in the adb backup routines. The backup command only runs for a few seconds and produces a near empty file.
