### ISSUE TITLE
provide pre-built jars

### ISSUE THREAD

**Issue by graingert** [nelenkov/android-backup-extractor#47]

**Comment by gronostajo** [comment]
Running `gradle shadowJar` will produce a ready-to-use JAR. Could you post it on GitHub as a release @nelenkov? It would make this useful tool available for non-developers.

**Comment by ariccio** [comment]
Please. I'm not a Java guy, and I can't get it to build...

**Comment by nelenkov** [comment]
Here it is: https://github.com/nelenkov/android-backup-extractor/releases/tag/v1.0

Not promises that I'll be able to release regularly though, compiling from source is recommended.
