### ISSUE TITLE
Error: Don't know how to process version '4'

### ISSUE THREAD

**Issue by OnePlus3T** [nelenkov/android-backup-extractor#48]
Apparently the backup file format has changed.
With an Android 7.0 phone connected to USB on a linux pc:

~/backup$ adb backup -all
Now unlock your device and confirm the backup operation.
~/backup$ ls -s backup.ab
8448 backup.ab
~/backup$ perl  ~/bin/backupdecrypt.pl --compress --debug   AES-backup.ab out.tar
Error: Don't know how to process version '4'...

Extract method found elsewhere doesn't work either:
~/backup$ du -sh backup.ab
8.3M	backup.ab
~/backup$  (printf "\x1f\x8b\x08\x00\x00\x00\x00\x00" ; tail -n +5 backup.ab) | tar xizf -

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
~/backup$ du -sh apps
14M	apps

Unsure if everything is there...

**Comment by OnePlus3T** [comment]
Forgot to mention:
~/backup$ head -4 backup.ab
ANDROID BACKUP
4
1
none

**Comment by nelenkov** [comment]
The Perl script you are using is not directly related to this project. Get latest Java code from this repository and try it, version 4 has been supported for a while.

**Comment by OnePlus3T** [comment]
Sorry for the confusion. I did try abe.jar too an hour ago and got some java error .. but must have mistyped something because trying to reproduce the error just now resulted in an unencrypted, unpacked backup. Yay!

~//backup/android-backup-extractor-20160710-bin$ java -jar  abe.jar unpack ../AES-backup.ab backup.tar
Backup encrypted, enter password (will NOT be displayed):
Password:
~/backup/android-backup-extractor-20160710-bin$ tar -tf backup.tar > /dev/null ; echo $?
0
~/backup/android-backup-extractor-20160710-bin$ 
~/backup/android-backup-extractor-20160710-bin$ du -sh backup.tar
13M	backup.tar

 
Sorry for the erroneous report and thanks for the usefull utility 

Indeed google bumped the file version already a year ago
https://android.googlesource.com/platform/frameworks/base/+/2c1ba9a961d4f96c26df260ee437655ad9e7c03e%5E%21/services/backup/java/com/android/server/backup/BackupManagerService.java

**Comment by nelenkov** [comment]
Glad it works for you.
