### ISSUE TITLE
fails to compile with gradle

### ISSUE THREAD

**Issue by superbonaci** [nelenkov/android-backup-extractor#51]
$ gradle
Download https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.0.3/shadow-1.0.3.pom
Download https://jcenter.bintray.com/jdom/jdom/1.1/jdom-1.1.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm/4.1/asm-4.1.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-parent/4.1/asm-parent-4.1.pom
Download https://jcenter.bintray.com/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-commons/4.1/asm-commons-4.1.pom
Download https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/25/commons-parent-25.pom
Download https://jcenter.bintray.com/org/apache/apache/9/apache-9.pom
Download https://jcenter.bintray.com/org/jdom/jdom/1.1/jdom-1.1.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.pom
Download https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.0.3/shadow-1.0.3.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm/4.1/asm-4.1.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-commons/4.1/asm-commons-4.1.jar
Download https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://jcenter.bintray.com/org/jdom/jdom/1.1/jdom-1.1.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.jar

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\temp\android-backup-extractor-master\build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'android-backup-extractor-master'.
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin']
   > No signature of method: org.gradle.internal.classloader.FilteringClassLoader.allowPackage() is applicable for argument types: (java.lang.String) values: [org.apache.tools.zip]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.083 secs

**Comment by acuna-personal** [comment]
It have a [Sourceforge](https://sourceforge.net/projects/adbextractor) page, where you can download the compiled versions for different platforms, is there's need to build it manually?

**Comment by nelenkov** [comment]
The sourceforge page is by a third party, I have no idea how recent the code they use is.

**Comment by acuna-personal** [comment]
Ah... that's so... so unexpected!) But I think they won't do such a great work and humble put it without any authors...

**Comment by marksutt** [comment]
@acuna-personal 
If you use ./gradlew from the repo, it should build without a problem.
I guess you used a newer version of gradle, which was incompatible with the shadow plugin version used.

Nevertheless I upgraded gradle and the shadow plugin to the current version.

**Comment by nelenkov** [comment]
Fixed thanks to PR by @marksutt .

**Comment by acuna-personal** [comment]
@marksutt thanks, but I have no problems with compile) I only tried to help the mate above.

**Comment by marksutt** [comment]
@acuna-personal  My bad, sorry.
I tried the same, but picked the wrong name.

**Comment by acuna-personal** [comment]
@marksutt ah, okay, don't worry) But authors see all messages anyway without links to his name, it's only way to show whom you addresses, no more.
