### ISSUE TITLE
java.security.InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by mreis1** [nelenkov/android-backup-extractor#52]
```
IvParameterSpec ivSpec = new IvParameterSpec(IV);
c.init(Cipher.DECRYPT_MODE, new SecretKeySpec(userKey.getEncoded(), "AES"), ivSpec);
byte[] mkCipher = hexToByteArray(masterKeyBlobHex);
byte[] mkBlob = c.doFinal(mkCipher);
```

While debugging I noticed that the app crashes right after executing the line 127 which calls `c.init(...`

This is the values evaluated during runtime before the app crashes: 

- **ivSpec** has a 16 byte array with the following values.
```[-107, -89, -89, 112, -74, 39, 37, 88, 80, 55, -78, 8, -13, 19, 31, 121]```

- userKey.getEncoded() is returning a 32 byte array 
```[81, 36, 65, 10, -38, 57, 97, 27, 81, -6, -1, 21, 67, -97, 76, -114, 119, -38, 61, 111, -40, -63, -6, -116, -10, 117, 84, 59, -93, 102, 34, 48] ```

- when I call new SecretKeySpec(userKey.getEncoded(), "AES") i get an object with a key with this 32 byte's array: [81, 36, 65, 10, -38, 57, 97, 27, 81, -6, -1, 21, 67, -97, 76, -114, 119, -38, 61, 111, -40, -63, -6, -116, -10, 117, 84, 59, -93, 102, 34, 48]

The the app crashes: **java.security.InvalidKeyException: Illegal key size**

### About the environement: 
I tested on both java 7 and java 8.
![android-backup-unpack-abe](https://cloud.githubusercontent.com/assets/1719667/26025476/0809035a-37e9-11e7-9bcf-eee64d00af0d.png)

**Comment by nelenkov** [comment]
Install the unlimited strength JCE extension, see readme

**Comment by mreis1** [comment]
@nelenkov as far as I know all i had to do is place the contents of JCE in `$JAVA_HOME/jre/lib/security/ ` which I did even knowing that they were already installed. 

```
$ cd $JAVA_HOME/jre/lib/security/
$ tree
├── US_export_policy.jar    <----
├── blacklist
├── blacklisted.certs
├── cacerts
├── java.policy
├── java.security
├── local_policy.jar    
└── trusted.libraries
```

Am I missing something?

**Comment by mreis1** [comment]
Ok, I managed to fix the issue. 
Since I'm not a Java developer I didn't noticed that my old eclipse installation was using a JRE 1.7  Include the JRE in my list of installed JRE + updating the project to the use that specific JRE did the trick. 


Here some screenshots if some else faces the same issue: 
![screenshot 2017-05-13 as 18 39 31](https://cloud.githubusercontent.com/assets/1719667/26027456/85d19fc0-380e-11e7-8f58-1a94d9cf60ad.png)
![screenshot 2017-05-13 as 18 50 23](https://cloud.githubusercontent.com/assets/1719667/26027455/85ccfb50-380e-11e7-8a56-c521a8ac27ec.png)
![screenshot 2017-05-13 as 18 50 54](https://cloud.githubusercontent.com/assets/1719667/26027454/85cb5034-380e-11e7-9427-cab435a06d90.png)

![screenshot 2017-05-13 as 18 50 37](https://cloud.githubusercontent.com/assets/1719667/26027453/85c5f99a-380e-11e7-9d9b-b97770296395.png)

**Comment by nelenkov** [comment]
Setting JAVA_HOME to the latest JDK and using the Gradle script should be easier, but glad this works for you.
