### ISSUE TITLE
Unable to initialize main class org.nick.abe.Main

### ISSUE THREAD

**Issue by hohenheim1618** [nelenkov/android-backup-extractor#87]
This is on a Manjaro Linux XFCE machine, using java-11-openjdk

I'm trying to convert my backup.ab to a backup.tar using the following command:

`java -jar /usr/share/java/android-backup-extractor-git/abe.jar unpack backup.ab backup.tar`

(My abe.jar file is in /usr/share/java/android-backup-extractor-git/abe.jar)

For context, I initially ran this command using java-8-openjdk. I then realized that ABE actually needs Java 11, so I installed Java 11, set it as my default environment, and reran the above command. Even so, I get this error:

`Error: Unable to initialize main class org.nick.abe.Main
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider`

I'm not entirely sure if the error has to do with ABE itself, or if it's a broader error with my Java environment. However, thought I'd post this issue here just in case this is an ABE issue. Happy to provide any other info about my system, if it helps. Thanks!

**Comment by hohenheim1618** [comment]
**Update**: This was easily fixed when I switched my original command from:

`java -jar /usr/share/java/android-backup-extractor-git/abe.jar unpack backup.ab backup.tar`

To:

`abe unpack backup.ab backup.tar`

Sorry for not checking this first before posting the issue! Should I keep it open, just to check why the original command didn't work? No worries if not, happy to mark this as resolved.

**Comment by superbonaci** [comment]
You can close the issue yourself.
