### ISSUE TITLE
Pre-built binaries are missing

### ISSUE THREAD

**Issue by boramalper** [nelenkov/android-backup-extractor#92]

**Comment by nelenkov** [comment]
Do provide details about where you looked, but should be on the releases page.

**Comment by robertgroh** [comment]
Looking at the release page (https://github.com/nelenkov/android-backup-extractor/releases),
only the build [20220109062628-4c55371](https://github.com/nelenkov/android-backup-extractor/releases/tag/20220109062628-4c55371) list three assets, which includes the ´abe.jar´, newer ones list only two assets, missing the abe.jar
![image](https://user-images.githubusercontent.com/5773739/153760205-a6a5f7a5-5a38-44c3-a624-0417373113c0.png)

**Comment by boramalper** [comment]
Exactly, I thought it was pretty obvious that it's not on the releases page.

**Comment by nelenkov** [comment]
@boramalper Not at all obvious, if you are taking the time to open issue providing some details is the least you can do (thanks @robertgroh !).

TravisCI works in mysterious ways, but should be fixed now, with the added bonus of smaller jars.

**Comment by boramalper** [comment]
@nelenkov I appreciate your work, no hard feelings. :)
